### ISSUE TITLE
Autosplit is not working?

### ISSUE THREAD

**Issue by Apozoic** [brandondong/POE-LiveSplit-Component#17]
I did everything according to your guide.

1. Downloaded LiveSplit from the official website
2. Edited splits
3. Activated autosplit

But the timer just doesn't switch when entering a new zone

**Comment by brandondong** [comment]
The tool has been working fine on my side.

A couple of things that may help diagnose the issue:
1. Please attach your splits file (there should be a .lss file after you have saved your splits).
2. Open the log file specified in the "Client log file location" setting and verify there are recent entries recording the zones you have entered. It would be most helpful if you could copy and paste a short snippet here.

If the issue is not identified after those two steps, I can send over a version of the autosplitter with additional logging to see what's really going on. Thanks.
