### ISSUE TITLE
How do I use the lab speedrun?

### ISSUE THREAD

**Issue by TrueEdge** [brandondong/POE-LiveSplit-Component#5]
So I am completetly new to the programm and wanted to time my lab. But it just stops the timer when I enter the next area. I also saw a streamer which hase 1st trial, 2nd trial, 3rd trial and izaro kill as splits. but when I add them they get triggered in the next area, how do i do it that they only trigger when i enter aspirants trial and so on?

**Comment by brandondong** [comment]
Hi, the streamer was most likely manually triggering their own splits.

The way this tool works for lab speedrunning is that it starts the timer on the first labyrinth zone entered and splits on all subsequent lab zones. The idea is that the runner would create the required number of splits for their route to see a complete timing breakdown of each zone.

I can work on adding an option to instead only split on the three trials instead of every zone. I'm not super familiar with lab speedrunning myself; would this be upon entering Aspirant's Trial or the zone after? Note that the final Izaro kill cannot be automatically split on as there's not a reliable way to detect it in the client logs as far as I understand.

**Comment by TrueEdge** [comment]
Ye on entering Aspirant's Trial

Also here is vod of him https://www.twitch.tv/videos/545323156 and I don't think he split it manually

**Comment by brandondong** [comment]
Thanks, I can't tell if they're splitting manually or not but I know they are not using this tool for it. I will work on adding this feature.

**Comment by brandondong** [comment]
I have added an option to only split on Aspirant's Trial zones and have changed the timer to automatically start when using the lab activation device rather than upon entering the first lab zone.

To get the changes, restart LiveSplit and an update prompt should appear in a few seconds.

If you run into any issues, please let me know.
