### ISSUE TITLE
Livesplit not saving my new personal best

### ISSUE THREAD

**Issue by keld0rn** [brandondong/POE-LiveSplit-Component#6]
I originally created an issue about this in the main Livesplit issues but someone suggested to me that the problem is probably related to the Auto Splitter and that I should report it here.

I'm doing some path of exile speedrunning and for some reason livesplit refuses to save my personal best. The way I have my livesplit setup is that it automatically splits upon me entering specific areas and at the end for the final split I do it manually as it's a boss kill and livesplit can't do it automatically. So at the end of the run, I do the final split, it's better than my personal best (shown as blue) and then I attempt to save it - I've done it mutiple ways, neither worked:
- I tried to reset, then close livesplit but not before clicking on the 'yes I do want to save'
- I tried to just close livesplit and then click on the 'yes I do want to save'
- I tried to right click livesplit - save splits, then exit livesplit

The odd thing is that I created a different set of splits, just to test this, tried each of those 3 ways of saving personal best - they all worked. But none of those work for my regular splits.

Here's how my regular splits are setup 
![image](https://user-images.githubusercontent.com/15522298/74388197-b5752880-4df2-11ea-9b00-e3626c980518.png)

I have compare against -> personal best / real time

My splits file:
[Path of Exile - Act 5 Kitava Kill - Copy.zip](https://github.com/brandondong/POE-LiveSplit-Component/files/4198122/Path.of.Exile.-.Act.5.Kitava.Kill.-.Copy.zip)

**Comment by brandondong** [comment]
I have used your split settings, traversed the zones, and manually triggered the final split. For me, the personal best updates every time.

However, I can reproduce the exact behavior if I set compare against -> personal best / game time. Was this changed at some point? Your layout settings use Timing Method -> Real Time instead of the default of Current Timing Method so if it was accidentally set to game time, it wouldn't be easily noticeable visually.

I was able to produce a number strange bugs with compare against -> personal best / game time without any autosplitter active.

If you're certain that compare against -> personal best / game time was never set, could you try just zooming through the zone wave points as I did and seeing if the personal best is updated? You can make a copy of the splits file as to not ruin your historical data. If that doesn't work, could you try manually triggering all the splits and saving? Finally, if that still doesn't work, could you disable my autosplitter and try the same thing? Thanks.

**Comment by keld0rn** [comment]
> I have used your split settings, traversed the zones, and manually triggered the final split. For me, the personal best updates every time.
> 
> However, I can reproduce the exact behavior if I set compare against -> personal best / game time. Was this changed at some point? Your layout settings use Timing Method -> Real Time instead of the default of Current Timing Method so if it was accidentally set to game time, it wouldn't be easily noticeable visually.
> 
> I was able to produce a number strange bugs with compare against -> personal best / game time without any autosplitter active.
> 
> If you're certain that compare against -> personal best / game time was never set, could you try just zooming through the zone wave points as I did and seeing if the personal best is updated? You can make a copy of the splits file as to not ruin your historical data. If that doesn't work, could you try manually triggering all the splits and saving? Finally, if that still doesn't work, could you disable my autosplitter and try the same thing? Thanks.

I have changed from game time to real time (or the other way round) a couple of times in the last few weeks. At the time I didn't think it made any difference so I didn't think to mention it.

I'll try doing another run with 'real time' in both the layout settings and the comparison thing and see if it updates my PB.
