### ISSUE TITLE
Adding more splits for auto splitting

### ISSUE THREAD

**Issue by Psylenceo** [brandondong/POE-LiveSplit-Component#8]
I was hoping to use the auto split to help me and anyone else who is interested in improving their leveling times either for league start or for racing. In particular, I was hoping to use live split to assist in tracking how much time was spent in a hub like lioneye's watch. Something like:

Twilight strand
Lioneye's watch
strand
mudflats
submerge passage waypoint
tidal island
lioneye's watch
submerged passage

The above splits auto split fine until I use log out to get back to lioneye's watch faster. Is this part of the limitation on how the game logs zones based on acts? Or can this be improved to actually detect revisiting a zone and if that zone is next on the split list to advance?

**Comment by brandondong** [comment]
There is no technical limitation due to game logs. This is more of a design issue.

With LiveSplit, users can create/delete/rename their splits as desired. In the general case, there is no one to one mapping between the zones they've chosen to autosplit on and their currently configured split names. As such, the tool was designed so that split names would never matter with regards to autosplitting.

The zones they've chosen to autosplit on can be thought of as one unordered set. If the player enters a zone in that set and has not entered it before, the timer simply finishes the current split and moves on to the next. With the Generate Splits button and the ability to reorder created splits, this should cover most use cases with the advantage of still being simple to reason about, having consistent behavior with labyrinth mode where generating splits is not supported, and playing nicely with cases where a user may want to insert their own manually triggered splits into their runs (e.g. boss kills).

To support the above described use case, split names will now have to matter for autosplitting. If that happens in one instance, it may be confusing if everything else remains split name unaware. However, I don't have a clear idea of what supporting split names globally should look like.

The best resolution I can think of for now is just to make this a hidden feature for this one specific use case. If the next zone is in the zone autosplit set + you've already encountered this zone + your current split name is an **exact** case sensitive match to the generated split name, then split anyways.

Thoughts? Suggestions?

**Comment by Psylenceo** [comment]
That sounds fine to me to make the Names be exact matchs to help reduce miss splits. Hmmmm but about deaths and accidentally clicking return to town, using a scroll to open inventory space, or server disconnects.

If I was more used to using git I may be able to help test and debug the code. Since I think MS visual studio code would let me edit test and debug. Your thoughts?

**Comment by brandondong** [comment]
I didn't even consider those cases but they should be rare and I don't see an easy way of handling them.

If you would like to help test it, that would be very easy to arrange; no need to set up a full development environment. I just need to find some time to implement this first.

**Comment by Psylenceo** [comment]
I already have vs code with platform io and other programs installed. I just need to figure out how to get your code to compile. And get a better grasp on how the code parses, separates, and calls the functions. And I'd like to see if theres a way to distinguish what part a character is on. Just not sure I have enough time or how to make the client log be less cluttered since it also holds chat data.

**Comment by brandondong** [comment]
I have finished implementing the necessary changes (https://github.com/brandondong/POE-LiveSplit-Component/commit/33a83b97aa4e86f13d5fe537c291821dfe2822b8). As this is a hidden feature, I am not going to push out an update.

To get these changes, close LiveSplit, navigate to its folder, open the Components folder, and delete POELiveSplitComponent.dll (no splits or settings data will be lost). Then, reopen LiveSplit and it should re-download that dll file. Please let me know if you run into any issues.

**Comment by brandondong** [comment]
If you're interested in making code changes to this project, there really shouldn't be any steps required beyond https://github.com/brandondong/POE-LiveSplit-Component#development-setup. If you have more details about exactly what's not working, I could help diagnose the issue.

**Comment by Psylenceo** [comment]
I've tested it about 12 times now with the new POELiveSplitComponent.dll, at leat the .dll that Livesplit downloads. And it still does not perform the repeat splits. I'll try to make a recording of what it does, what I'd like it to do, and the folder with all the live split settings. So that we can figure out if It is something I'm doing, Livesplit is downloading the old .dll, or if the code is not correctly catching the additional points for splits.

**Comment by brandondong** [comment]
Reading over your original message again, I suspect I know what the issue is. I interpret a split with zone name X as the time it takes for moving from the previous split's zone to X. See https://www.youtube.com/watch?v=difLKG14330 or https://www.youtube.com/watch?v=yp3FbFB7VVU as an example. I implemented the new feature with that in mind. Whereas I believe you interpret a split with zone name X as the time it takes for moving from X to the next split's zone.

It's fairly subjective but from what I've seen, the former interpretation is widely used so I'm inclined to keep the current logic (if the next zone is in the zone autosplit set + you've already encountered this zone + your **current** split name is an exact case sensitive match to the generated split name, then split anyways).

**Comment by Psylenceo** [comment]
Curious if I can even post here, since I've been flagged. But here is the link to what livesplit is doing: https://youtu.be/6c4Y5xcmu6E

And here is the link to my botched attempt at showing how I wanted the extra splits to work dfor re-visiting a zone: https://youtu.be/Jq5_fg_6iTE

But, I think you are understanding what I'd like the splits to do. But just in case the videos don't make sense.

If I set up a split list like this:

Twilight strand
Lioneyes
coast
mudflats
submerged passage
coast
tidal islands
lioneyes
submerged passage
etc

Or even if i omit the 2nd coast split , because it is not important since it would represent the amount of time it took to get from the waypoint to the loading into the tidal Island after teleporting from the submerged passage.

However, when I log out of tidal then log back in to get the free fast teleport to Lioneye's, I do NOT get an auto split to show how much time I spent in tidal island and began tracking how much time I spent in lioneye's for the 2nd time, before I teleport back to the submerged passage to finish the act progression.

Equally like above once I teleport into to submerged passage after already going in just to get the waypoint, there is no autosplit, I have to manually progress the splits when I leave tidal island and load into Lioneye's, then manually split again once I load into submerged passage.

 I was hoping we could get the ability to have autosplits trigger even if we re-entered a zone either do to a teleport, teleport scroll, or log-out / login free teleport.

**Comment by brandondong** [comment]
Thanks for going through the effort of making a video.

I'm not sure if you read my above [comment](https://github.com/brandondong/POE-LiveSplit-Component/issues/8#issuecomment-643089158) but to summarize, the general consensus in the POE racing community as far as I know is that a split with zone name X represents the time it takes to reach X. See https://www.youtube.com/watch?v=difLKG14330 or https://www.youtube.com/watch?v=yp3FbFB7VVU as an example. I have implemented the feature accordingly to match this model.

Your splits use a model where if you have a split named X followed by a split named Y, split X represents the time it takes to reach Y. The zone revisiting autosplitting should work if you simply remove your first split (Twilight Strand).
